name: Docker Image 

on:
  push:
    branches: [ "main" ]

jobs:

  create-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hello-world:latest --tag hello-world:1.5
  
  push-image:
  
     runs-on: ubuntu-latest

     steps:

      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag hello-world:latest --tag mini-app:1.5
        
      - name: Build the Docker image
      - uses: MaximilianoBz/dockerhub-buildpush@v1.1
        with:
          registry_url: docker.io
          repository_name: h4zan/mini-app
          user_name: ${{secrets.DOCKER_USERNAME}}
      # Docker Login Access Token, from: https://hub.docker.com/
          password: ${{secrets.DOCKER_PASSWORD}}
      # Image Build Version
          image_version: latest
      # Docker File Directory, Default Current Directory (.)
          docker_file: .
    
      
